### ISSUE TITLE
new transaction on home page

### ISSUE THREAD

**Issue by BUI-studies** [BUI-studies/kurkulyator#18]
one of the features on the Home page is the quick creation of a new transaction. So implement it. |

User should click the button, see the form, complete it, and send it. 

![Image](https://github.com/BUI-studies/kurkulyator/assets/104223028/f06ab16d-45ed-4498-8ef9-bfe03a82601c)

**Comment by AKot1988** [comment]
Hello. I have been added transactionForm to this branch and push changes to it. Can you check pls
