### ISSUE TITLE
use createElement util for all elements creations in the project

### ISSUE THREAD

**Issue by BUI-studies** [BUI-studies/kurkulyator#31]
make sure we have 3 creation functions. for - regular element, input and select. and use them **everywhere**. 

to do so you would need to refactor almost every render() method

**Comment by BUI-studies** [comment]
blocked until https://github.com/BUI-studies/kurkulyator/pull/20/files is merged

**Comment by AKot1988** [comment]
I've finished this task. Rafactored code visualy doent change anything (this was the expected result)
